name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell (Ubuntu & macOS)
        if: matrix.os != 'windows-latest'
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Roswell (Windows)
        if: matrix.os == 'windows-latest'
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /usr
          ROSWELL_BRANCH: master
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Rove
        run: ros install rove
      - name: Add source registry (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          mkdir -p ~/AppData/Local/config/common-lisp/source-registry.conf.d
          echo "(:tree \"`pwd`/\")" > ~/AppData/Local/config/common-lisp/source-registry.conf.d/ci.conf
      - name: Run tests
        shell: bash
        run: |
          PATH="~/.roswell/bin:$PATH"
          pwd
          cat ~/AppData/Local/config/common-lisp/source-registry.conf.d/*.conf
          ros -s alexandria -e '(prin1 (alexandria:hash-table-alist ASDF/SOURCE-REGISTRY:*SOURCE-REGISTRY*))'
          rove qlot.asd
